### ISSUE TITLE
证书无法续期

### ISSUE THREAD

**Issue by wrswap** [tokenssL/tokenssL#4]
正在检查即将过期的订单...
Traceback (most recent call last):
  File "/www/server/panel/plugin/tokenssl/src/AutoRenew.py", line 378, in <module>
    main_process()
  File "/www/server/panel/plugin/tokenssl/src/AutoRenew.py", line 364, in main_process
    renewal_expiring_cert()
  File "/www/server/panel/plugin/tokenssl/src/AutoRenew.py", line 334, in renewal_expiring_cert
    orders = get_expiring_orders()
  File "/www/server/panel/plugin/tokenssl/src/AutoRenew.py", line 310, in get_expiring_orders
    c = db.execute(check_sql)
sqlite3.OperationalError: no such column: renew_id

**Comment by xiaohuilam** [comment]
tokenssL was deprecated and a replacement is https://www1.hi.cn
